### ISSUE TITLE
Create new system for scene changing 

### ISSUE THREAD

**Issue by Major-Lag98** [Major-Lag98/Golf-N-Stuff#20]
Create a new system that can be used by other scripts to change scenes.
The containing functions will be public so they may be called by any script that is requiring scene change.
Next level can be assumed: current scene index + 1

Reference for scene change: https://docs.unity3d.com/ScriptReference/SceneManagement.SceneManager.LoadScene.html

**Comment by kendallcallison** [comment]
Due to wanting to implement a global score keeper I also went ahead and fixed the scene change in order to test the new global score kept in PlayerData. The "scene change button" Bug was fixed by the end state disabling the camera lock when the level is complete. **This will have to be kept in mind for when a pause is implemented.**
